### PR TITLE
see if py311 works okay

### PR DESCRIPTION
**Pull request by mikemhenry**
## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT License [here](https://github.com/OpenFreeEnergy/openfe/blob/main/LICENSE) and the **Developer Certificate of Origin** at <https://developercertificate.org/>.

### CODE REVIEW

**Comment by mikemhenry** [comment]
Inspired by https://github.com/OpenFreeEnergy/openfe/issues/507

**Review by dwhswenson — APPROVED** [review]
Looks like 3.11 works. I vote to include it in our testing matrix. Also means that wasn't the problem in #507.

**Comment by mikemhenry** [comment]
Okay if we only want to run a job on OSX, which python version do we want it to be? I can do that on this PR.

**Comment by mikemhenry** [comment]
Maybe just the latest? So python 3.11 on osx but skip the others? Or do we want to keep the oldest and the newest and just skip 3.10?

**Comment by IAlibay** [comment]
> Maybe just the latest? So python 3.11 on osx but skip the others? Or do we want to keep the oldest and the newest and just skip 3.10?

3.11 only is fine, that's what folks will pick up on a clean install.

**Review by IAlibay — APPROVED** [review]

**Comment by mikemhenry** [comment]
Got all the branch checks setup now as well

**Pull request merged**
