### PR TITLE
fix issue #1042 and also test openfecli for API breaks

### LINKED ISSUE #1042: API break runner is too noisy
I love the idea, but I think it needs a bit of refinement.

Is there any way to do an API break on the diff against main? As far as I'm aware it's not and it's complaining on changes done in other commits.

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [ ] Added a ``news`` entry

## Developers certificate of origin
- [ ] I certify that this contribution is covered by the MIT License [here](https://github.com/OpenFreeEnergy/openfe/blob/main/LICENSE) and the **Developer Certificate of Origin** at <https://developercertificate.org/>.

Fixes #1042

### CODE REVIEW

**Comment by mikemhenry** [comment]
Okay, so now I will add an api break and see if we get the new message

**Comment by mikemhenry** [comment]
Okay that worked! 
image
URL takes you here: https://github.com/OpenFreeEnergy/openfe/actions/runs/12321768691#step:check

**Comment by mikemhenry** [comment]
Now I will "fix" that change and lets see if it deletes the old comment

**Comment by mikemhenry** [comment]
Ah, if there is no failure then it doesn't delete the comment, will fix that now

**Comment by mikemhenry** [comment]
Sweet, it deleted the comment. I will do one more cycle of testing and then I think we will be good to go

**Comment by mikemhenry** [comment]
image
okay it had the break, now lets see if it deletes this comment and says things are fine

**Comment by mikemhenry** [comment]
cool, it works! 
image

**Comment by mikemhenry** [comment]
To test it I had to switch it to run on `pull_request` but that means the old version with `pull_request_target` would also run, so its cluttered with old bot messages, but I posted screenshots of the tests where it worked. To truly test it, we will just need to merge it and see how it behaves, but I did test it as much as I could.

**Review by atravitz — APPROVED** [review]

**Pull request merged**
