### PR TITLE
Update  `openfecli/tests/data/rbfe_results.tar.gz`

### PR DESCRIPTION
**Pull request by mikemhenry**
## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT License [here](https://github.com/OpenFreeEnergy/openfe/blob/main/LICENSE) and the **Developer Certificate of Origin** at <https://developercertificate.org/>.

### CODE REVIEW

**Review by richardjgowers — COMMENTED** [review]
this data is probably necessary for some tests, but annoyingly it's 7mb.  This is almost certainly the protein component in the transformation.  We could probably erase this (and make the transformation invalid), but maybe we should just bite the bullet and have this heavy test file

**Comment by mikemhenry** [comment]
@richardjgowers We could host it somewhere else and pull it down, like on S3 or something

**Comment by mikemhenry** [comment]
Just needs approval for merge

**Comment by dwhswenson** [comment]
I'm fine with this; @IAlibay : are we clear to go on this one?

**Review by IAlibay — APPROVED** [review]
Yeah let's just remember this one in case we need to clear up repo space later.

**Pull request merged**
