### PR TITLE
added check for element changes in openmm rbfe protocol

### LINKED ISSUE #144: RBFE Protocol element change mappings checks
This should happen as a pre-flight check

### PR DESCRIPTION
**Pull request by richardjgowers**
Fixes #144

### CODE REVIEW

**Comment by IAlibay** [comment]
> Ok this breaks all the tests as we currently often do this.  Once lomap gets patched we can fix our tests here.

Yeah you've pretty much moved the problem upstream from run 🤣 Do you want to remove the element checking code in utils whilst you're here?

**Comment by richardjgowers** [comment]
Done.

So I'm seeing elsewhere you take an average of masses.  If we're excluding element changes then this is not needed right? https://github.com/OpenFreeEnergy/openfe/blob/main/openfe/setup/_rbfe_utils/relative.py#L391

**Comment by IAlibay** [comment]
We should keep that in for now, it's part of the underlying perses stuff so technically I guess they do allow for element changes but don't by default?

**Review by IAlibay — APPROVED** [review]
Approving the changes I didn't make - if we could go ahead and merge with temporary switch from conda installing lomap2 to pip installing from main that'd be grand. That way I can move on with the mapping tests I need to get done for this afternoon. I can raise an issue for us to revert the change once the release is made and things are pushed over to conda-forge (which usually take several hours).

**Pull request merged**
