### PR TITLE
added note about the GUFE package

### LINKED ISSUE #306: [docs] explain existence of gufe package for developer minded people

### PR DESCRIPTION
**Pull request by mikemhenry**
fixes #306

Checklist
* [ ] Added a ``news`` entry

## Developers certificate of origin
- [ ] I certify that this contribution is covered by the MIT License [here](https://github.com/OpenFreeEnergy/openfe/blob/main/LICENSE) and the **Developer Certificate of Origin** at <https://developercertificate.org/>.

### CODE REVIEW

**Comment by mikemhenry** [comment]
I put the note in two spots, both seem like the "right" one and duplicating isn't too bad (I can make a macro if we want to put it everywhere there is a GUFE object/want to put it in more spots)

**Comment by mikemhenry** [comment]
@richardjgowers I was going to do a "for example, <link to SmallMoleculeComponent on GUFE> and <link to SmallMoleculeComponent on OpenFE>" but that might be unnecessary?

**Comment by richardjgowers** [comment]
@mikemhenry I added an extra sentence to explain a little which people should consult.  If you're happy with it merge this and/or copy it into both references.  A macro seems excessive for two usages

**Review by richardjgowers — APPROVED** [review]

**Comment by mikemhenry** [comment]
I will copy it in both spots and merge it in o7

**Pull request merged**
