### PR TITLE
CLI `fetch` command

### PR DESCRIPTION
**Pull request by dwhswenson**
This adds `openfe fetch`, with subcommands to fetch specific materials for tutorials, etc.

New materials can be added to the `fetchables.py` file and will be automatically added.

- [x] URL Fetcher
- [x] Package Resource Fetcher
- [x] Tests for fetchers
- [x] `fetch` command
- [x] tests for `fetch` command
- [x] Plugin for RHFE CLI tutorial
- [x] Tests for RHFE CLI tutorial plugin

### CODE REVIEW

**Comment by dwhswenson** [comment]
This should be ready for review now. Notes for reviewers:

1. The `RHFE_TUTORIAL` plugin is a placeholder. We'll have something named that, but it will bring down more files. This is just to get the test harness in place.
2. I think there will be some iteration on the design here. But this should be enough to get us through the workshop.

**Comment by richardjgowers** [comment]
currently broken
``` 
~/test/fetch_test > openfe fetch rhfe-cli-tutorial                                                   
Traceback (most recent call last):
  File "/home/richard/miniconda3/envs/openfe_dev/bin/openfe", line 8, in <module>
    sys.exit(main())
  File "/home/richard/miniconda3/envs/openfe_dev/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/richard/miniconda3/envs/openfe_dev/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/richard/miniconda3/envs/openfe_dev/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/richard/miniconda3/envs/openfe_dev/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/richard/miniconda3/envs/openfe_dev/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/richard/miniconda3/envs/openfe_dev/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/richard/miniconda3/envs/openfe_dev/lib/python3.10/site-packages/openfecli/fetching.py", line 67, in command
    directory.mkdir(parents=True, exist_ok=True)
AttributeError: 'str' object has no attribute 'mkdir'
```

**Review by richardjgowers — CHANGES_REQUESTED** [review]
didn't work locally, probably also needs a test by the looks of it

**Comment by dwhswenson** [comment]
@richardjgowers : you're on an old commit. Fetch the most recent.

This has 100% coverage, and the problem you're seeing was fixed in https://github.com/OpenFreeEnergy/openfe/pull/380/commits/aa580f6013a189950e191f11006b5ee212842601.

In the current file, the `mkdir` is on line 70. Your error reports it on line 67.

https://github.com/OpenFreeEnergy/openfe/blob/523dd6dcf58f06cdf4a2ee4598f892b02aa1239c/openfecli/fetching.py#L67-L71

**Review by richardjgowers — APPROVED** [review]

**Pull request merged**
