### PR TITLE
add fetch-depth to CI version check

### PR DESCRIPTION
**Pull request by IAlibay**
Nothing big, doesn't look like we had universal wheels on here either.

### CODE REVIEW

**Review by dwhswenson — APPROVED** [review]
Looks fine, but any particular reason to fetch the entire history? Is that needed?

**Comment by IAlibay** [comment]
tbh it's partially lazyness on trying to figure out how deep you have to get to pickup enough for version to be right

**Comment by IAlibay** [comment]
yeah 🤷🏽 I'm sure there's a happy medium, but it's also a 1s checkout so my incentive to try to work it out is pretty low

**Comment by mikemhenry** [comment]
When I saw it was 1 second still, I wasn't too worried about it

**Pull request merged**
