### PR TITLE
update LomapAtomMapper default settings to established best practices

### PR DESCRIPTION
**Pull request by richardjgowers**
## Developers certificate of origin
- [ ] I certify that this contribution is covered by the MIT License [here](https://github.com/OpenFreeEnergy/openfe/blob/main/LICENSE) and the **Developer Certificate of Origin** at <https://developercertificate.org/>.

### CODE REVIEW

**Comment by richardjgowers** [comment]
hmm this is causing a test to fail as a network now can't be constructed, I'll dig into this

**Comment by hannahbaumann** [comment]
We'll probably also have to update the `expected_transformations()` fixture in the `test_rbfe_tutorial.py`.

**Review by hannahbaumann — COMMENTED** [review]
lgtm once tests are passing

**Comment by mikemhenry** [comment]
@richardjgowers in hindsight this would have been good to put in the changelog to highlight the defaults changed, but also as a hint that we do work to figure out what the best practices are

**Comment by richardjgowers** [comment]
@mikemhenry I think the rule is that changelog is for post 1.0 changes

**Comment by mikemhenry** [comment]
Yes! You are right!

**Pull request merged**
