### PR TITLE
Check the ability to pass user charges

### PR DESCRIPTION
**Pull request by IAlibay**
Adds a test that both manually checks charge assignment (good for us) and that user supplied charges will get all the way through to the HTF (good for users).

## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT License [here](https://github.com/OpenFreeEnergy/openfe/blob/main/LICENSE) and the **Developer Certificate of Origin** at <https://developercertificate.org/>.

### CODE REVIEW

**Comment by IAlibay** [comment]
Anyone got any ideas why RTD is broken here?

**Comment by mikemhenry** [comment]
`AttributeError: 'TocTree' object has no attribute 'get_toctree_ancestors'`

Smells like we need to add a pin, looks like the issue is here https://github.com/pydata/pydata-sphinx-theme/issues/1412

I will give CI a bump since that might be all we need

**Comment by mikemhenry** [comment]
@IAlibay you should be good now :)

**Comment by IAlibay** [comment]
cheers @mikemhenry !

**Review by richardjgowers — APPROVED** [review]

**Pull request merged**
