### PR TITLE
test pydantic v2

### PR DESCRIPTION
**Pull request by mikemhenry**
## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT License [here](https://github.com/OpenFreeEnergy/openfe/blob/main/LICENSE) and the **Developer Certificate of Origin** at <https://developercertificate.org/>.

### CODE REVIEW

**Comment by mikemhenry** [comment]
This PR now actually sets us to pull in pydantic v2, but we use a pydantic.v1 import so we can support either. Do we want to add one CI job that checks to make sure things pass with `pydantic <2`? I was thinking that I could add a linux python 3.11 test for that

**Comment by richardjgowers** [comment]
@mikemhenry yeah a single job for v1 sounds good

**Review by richardjgowers — APPROVED** [review]

**Comment by mikemhenry** [comment]
@richardjgowers that worked, it messed up the names of the jobs a bit, is that okay?

**Comment by mikemhenry** [comment]
I'll do the same for gufe whatever we decide here

**Comment by richardjgowers** [comment]
@mikemhenry yeah I can't remember if there was a nice way to label what "<2" meant in the build matrix but it's functionally great right now at least

**Review by richardjgowers — APPROVED** [review]

**Pull request merged**
