### PR TITLE
Remove test skipping

### PR DESCRIPTION
**Pull request by mikemhenry**
Liked we talked about, this should make skipping the tests that fail when called with `--pyargs` the default, but our CI "opts in" to running the tests so they are still tested, but when end-users run the tests, everything passes since the tests will be skipped.

### CODE REVIEW

**Comment by dwhswenson** [comment]
I think I fixed the problem with tests failing on `--pyargs` in #358?

**Comment by IAlibay** [comment]
😅 yeah I think @dwhswenson was too fast sorry @mikemhenry !

**Comment by dwhswenson** [comment]
Could convert this PR into an opportunity to remove the `OFE_DOCKER_BUILD` / `SKIP_SOME_TESTS` env var, though?

**Comment by mikemhenry** [comment]
Haha no worries! And yes I can remove those args now!

**Review by IAlibay — APPROVED** [review]

**Comment by IAlibay** [comment]
we might have further issues (see #342 but at those specific tests seem to be running fine now)

**Pull request merged**
