### PR TITLE
Tell users to install the latest version of openfe

### PR DESCRIPTION
**Pull request by mikemhenry**
## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT License [here](https://github.com/OpenFreeEnergy/openfe/blob/main/LICENSE) and the **Developer Certificate of Origin** at <https://developercertificate.org/>.

### CODE REVIEW

**Comment by mikemhenry** [comment]
* I would like someone to check to see if I need that version somewhere else
* I will update the docs to use "latest" for image tags + installers (but recommend using a version number for production so nothing breaks)

**Comment by dwhswenson** [comment]
Installation page is the only place I see the version.... if you'll be updating single file and images to use `latest`, that'll fix there.

There's also an install listed on the note for Apple Silicon, but rather than add a version, maybe remove the whole note? I haven't tried it yet myself, but I hear someone did the mountain-moving effort to get ambertools to build.....

**Comment by mikemhenry** [comment]
> but I hear someone did the mountain-moving effort to get ambertools to build.....

heheh Does anyone on the dev team have an osx-arm64 computer? I am pro getting rid of the extra steps to get an x86-64 env, but I think it would be good if it was battle tested for a bit.

**Comment by dwhswenson** [comment]
> Does anyone on the dev team have an osx-arm64 computer?

I believe both @richardjgowers and I do. But I mentioned that I'm the zsh hipster (using it before it was default). As a result, my zsh is x86_64, which means that everything else in my stack is as well. I only discovered this when I was prepping the May tutorial and created a fresh account on my machine for that.

I can give the install a try in the fresh account.

**Comment by dwhswenson** [comment]
Ah crap. Leave it there. I install successfully, but get the ancient openfe version that we were seeing from an industrial partner as well. Let me see what I need to do to dump conda list across accounts (one logged into GitHub, one having the issue.) Will add it as a comment here soon, we can address it in a future PR.

Probably means you should add the version on the Apple Silicon for now, so this can get merged.

**Comment by mikemhenry** [comment]
I will do that! Also something I was thinking about is we don't have an installer for oxs-arm64, but I am not sure if it is worth building those as well. I think the Linux one has the most utility since it will work on codelab and also for any air gaped hpc installs.

**Comment by mikemhenry** [comment]
Added (so glad I could put a parsed-literal inside a warning block)!

**Comment by mikemhenry** [comment]
Just need to update the latest tags! Uploading them now so I can test them, and I think by the next release I will have the auto upload stuff done

**Comment by dwhswenson** [comment]
Pulling in openfe 0.6.1, ambertools 23.3, openmm 8.0.0 (to cite the usual suspects).

I've put in my 11 hours today. I'm not solving this now -- feel free to suggest if you have ideas! (Oh, are we supposed to support Python 3.11? I felt like someone in our stack didn't like that, maybe that's why I'm pulling down nonsense? Still, not solving tonight.)

<details><summary>$ conda list</summary>

```
# packages in environment at /Users/openfe/mambaforge/envs/openfe_env:
#
# Name                    Version                   Build  Channel
ambertools                23.3            py311ha883923_1    conda-forge
amberutils                21.0                     pypi_0    pypi
anyio                     3.7.1              pyhd8ed1ab_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py311he2be06e_3    conda-forge
arpack                    3.7.0                h58ebc17_2    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.3              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
aws-c-auth                0.7.0                hf4e22b4_2    conda-forge
aws-c-cal                 0.6.0                h43a37b4_0    conda-forge
aws-c-common              0.8.23               hb547adb_0    conda-forge
aws-c-compression         0.2.17               h31a6291_1    conda-forge
aws-c-event-stream        0.3.1                h1e1aaf7_1    conda-forge
aws-c-http                0.7.11               h3107daf_0    conda-forge
aws-c-io                  0.13.28              hf096fb3_0    conda-forge
aws-c-mqtt                0.8.14               h9418dbe_2    conda-forge
aws-c-s3                  0.3.13               h79b0d72_2    conda-forge
aws-c-sdkutils            0.1.11               h31a6291_1    conda-forge
aws-checksums             0.1.16               h31a6291_1    conda-forge
aws-crt-cpp               0.20.3               h0918d87_4    conda-forge
aws-sdk-cpp               1.10.57             h6f3a27c_17    conda-forge
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.4               hc338f07_0    conda-forge
boost                     1.78.0          py311h5c64717_4    conda-forge
boost-cpp                 1.78.0               h9ed8d21_3    conda-forge
brotli                    1.0.9                h1a8c8d9_9    conda-forge
brotli-bin                1.0.9                h1a8c8d9_9    conda-forge
brotli-python             1.0.9           py311ha397e9f_9    conda-forge
bson                      0.5.9                      py_0    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.19.1               hb547adb_0    conda-forge
c-blosc2                  2.10.0               h068da5f_0    conda-forge
ca-certificates           2023.5.7             hf0a4a13_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.3.1              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            h1e71087_1016    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py311hae827db_3    conda-forge
cftime                    1.6.2           py311h4add359_1    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
click                     8.1.6           unix_pyh707e725_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.3              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.0           py311he4fd1f5_0    conda-forge
coverage                  7.2.7           py311heffc1b2_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    3.0.0           py311ha891d26_0    conda-forge
debugpy                   1.6.7           py311ha397e9f_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
edgembar                  0.2                      pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.2              pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hb7217d7_1    conda-forge
fftw                      3.3.10          nompi_h3046061_108    conda-forge
flit-core                 3.9.0              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h82840c6_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.41.0          py311heffc1b2_0    conda-forge
freetype                  2.12.1               hd633e50_1    conda-forge
freetype-py               2.3.0              pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               h0186832_0    conda-forge
greenlet                  2.0.2           py311ha891d26_1    conda-forge
gufe                      0.6.1              pyhd8ed1ab_0    conda-forge
hdf4                      4.2.15               h8111dcc_6    conda-forge
hdf5                      1.14.1          nompi_h3aba7b3_100    conda-forge
icu                       72.1                 he12128b_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
importlib_resources       6.0.0              pyhd8ed1ab_1    conda-forge
ipykernel                 6.24.0             pyh5fb750a_0    conda-forge
ipython                   8.14.0             pyhd1c38e8_0    conda-forge
ipywidgets                8.0.7              pyhd8ed1ab_0    conda-forge
jax                       0.4.13             pyhd8ed1ab_0    conda-forge
jaxlib                    0.4.12          cpu_py311h2dd720e_1    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.3.0              pyhd8ed1ab_1    conda-forge
json5                     0.9.14             pyhd8ed1ab_0    conda-forge
jsonschema                4.18.4             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.7.1           pyhd8ed1ab_0    conda-forge
jupyter-lsp               2.2.0              pyhd8ed1ab_0    conda-forge
jupyter_client            8.3.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.1           py311h267d04e_0    conda-forge
jupyter_events            0.6.3              pyhd8ed1ab_0    conda-forge
jupyter_server            2.7.0              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab                4.0.3              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.23.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.8              pyhd8ed1ab_0    conda-forge
khronos-opencl-icd-loader 2023.04.17           h1a8c8d9_0    conda-forge
kiwisolver                1.4.4           py311hd6ee22a_1    conda-forge
krb5                      1.21.1               h92f50d5_0    conda-forge
lcms2                     2.15                 hd835a16_1    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libabseil                 20230125.3      cxx17_h13dd4ca_0    conda-forge
libaec                    1.0.6                hb7217d7_1    conda-forge
libblas                   3.9.0           17_osxarm64_openblas    conda-forge
libbrotlicommon           1.0.9                h1a8c8d9_9    conda-forge
libbrotlidec              1.0.9                h1a8c8d9_9    conda-forge
libbrotlienc              1.0.9                h1a8c8d9_9    conda-forge
libcblas                  3.9.0           17_osxarm64_openblas    conda-forge
libcurl                   8.2.0                hc52a3a8_0    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libdeflate                1.18                 h1a8c8d9_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           12_2_0_hd922786_31    conda-forge
libgfortran5              12.2.0              h0eea778_31    conda-forge
libglib                   2.76.4               h24e9cb9_0    conda-forge
libgrpc                   1.56.2               h9075ed4_0    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
libjpeg-turbo             2.1.5.1              h1a8c8d9_0    conda-forge
liblapack                 3.9.0           17_osxarm64_openblas    conda-forge
libllvm14                 14.0.6               hd1a9a77_3    conda-forge
libnetcdf                 4.9.2           nompi_h9fa6108_109    conda-forge
libnghttp2                1.52.0               hae82a92_0    conda-forge
libopenblas               0.3.23          openmp_hc731615_0    conda-forge
libpng                    1.6.39               h76d750c_0    conda-forge
libprotobuf               4.23.3               hf32f9b9_0    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libsqlite                 3.42.0               hb31c410_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libtiff                   4.5.1                h23a1a89_0    conda-forge
libwebp-base              1.3.1                hb547adb_0    conda-forge
libxcb                    1.15                 hf346824_0    conda-forge
libxml2                   2.11.4               he3bdae6_0    conda-forge
libxslt                   1.1.37               h1728932_1    conda-forge
libzip                    1.9.2                h76ab92c_1    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
llvm-openmp               16.0.6               h1c12783_0    conda-forge
llvmlite                  0.40.1          py311hea943cd_0    conda-forge
lomap2                    2.3.1              pyhd8ed1ab_0    conda-forge
lxml                      4.9.3           py311hbafe683_0    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
markupsafe                2.1.3           py311heffc1b2_0    conda-forge
matplotlib-base           3.7.2           py311h3bc9839_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mdtraj                    1.9.8           py311h06bfd7f_2    conda-forge
mistune                   3.0.0              pyhd8ed1ab_0    conda-forge
ml_dtypes                 0.2.0           py311h9e438b8_1    conda-forge
mmpbsa-py                 16.0                     pypi_0    pypi
mpiplus                   v0.0.2             pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.7.1              pyhd8ed1ab_1    conda-forge
nbformat                  5.9.1              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h7ea286d_0    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
netcdf-fortran            4.6.1           nompi_hb96c8d4_101    conda-forge
netcdf4                   1.6.4           nompi_py311h724ebb5_101    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
nose                      1.3.7                   py_1006    conda-forge
notebook                  7.0.0              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
numba                     0.57.1          py311hbf3c4e2_0    conda-forge
numexpr                   2.8.4           py311h4eec4a9_0    conda-forge
numpy                     1.23.5          py311ha92fb03_0    conda-forge
ocl_icd_wrapper_apple     1.0.0                h27ca646_0    conda-forge
openfe                    0.6.1              pyhd8ed1ab_0    conda-forge
openff-amber-ff-ports     0.0.3              pyh6c4a22f_0    conda-forge
openff-forcefields        2023.06.0          pyh1a96a4e_0    conda-forge
openff-interchange        0.3.8              pyhd8ed1ab_0    conda-forge
openff-interchange-base   0.3.8              pyhd8ed1ab_0    conda-forge
openff-models             0.0.5              pyh1a96a4e_1    conda-forge
openff-toolkit            0.14.0             pyhd8ed1ab_3    conda-forge
openff-toolkit-base       0.14.0             pyhd8ed1ab_3    conda-forge
openff-units              0.2.1              pyh1a96a4e_0    conda-forge
openff-utilities          0.1.9              pyh1a96a4e_0    conda-forge
openjpeg                  2.5.0                hbc2ba62_2    conda-forge
openmm                    8.0.0           py311h500f5fd_1_khronos    conda-forge
openmmforcefields         0.11.2             pyhd8ed1ab_1    conda-forge
openmmtools               0.23.1             pyhd8ed1ab_0    conda-forge
openssl                   3.1.1                h53f4e23_1    conda-forge
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
overrides                 7.3.1              pyhd8ed1ab_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
packmol                   20.2.2               h9318095_1    conda-forge
packmol-memgen            2023.2.24                pypi_0    pypi
pandas                    2.0.3           py311h9e438b8_1    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
panedr                    0.7.1              pyhd8ed1ab_0    conda-forge
parmed                    4.1.0           py311ha397e9f_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pbr                       5.11.1             pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hb34f9b4_0    conda-forge
pdb4amber                 22.0                     pypi_0    pypi
pdbfixer                  1.9                pyh1a96a4e_0    conda-forge
perl                      5.32.1          4_hf2054a2_perl5    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.0.0          py311h095fde6_0    conda-forge
pint                      0.21               pyhd8ed1ab_0    conda-forge
pip                       23.2               pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h27ca646_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              3.9.1              pyhd8ed1ab_0    conda-forge
plugcli                   0.2.0              pyhd8ed1ab_0    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
prometheus_client         0.17.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.39             pyha770c72_0    conda-forge
prompt_toolkit            3.0.39               hd8ed1ab_0    conda-forge
psutil                    5.9.5           py311he2be06e_0    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py-cpuinfo                9.0.0              pyhd8ed1ab_0    conda-forge
pycairo                   1.24.0          py311h3a69ff1_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.11         py311heffc1b2_0    conda-forge
pyedr                     0.7.1              pyhd8ed1ab_0    conda-forge
pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
pymbar                    4.0.1           py311h4add359_2    conda-forge
pymsmt                    22.0                     pypi_0    pypi
pyobjc-core               9.2             py311hb702dc4_0    conda-forge
pyobjc-framework-cocoa    9.2             py311hb702dc4_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytables                  3.8.0           py311ha2ad9a0_2    conda-forge
python                    3.11.4          h47c9636_0_cpython    conda-forge
python-constraint         1.4.0                      py_0    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.17.1             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    3_cp311    conda-forge
pytraj                    2.0.6                    pypi_0    pypi
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py311he2be06e_5    conda-forge
pyzmq                     25.1.0          py311hb1af645_0    conda-forge
rdkit                     2023.03.2       py311hee821e4_0    conda-forge
re2                       2023.03.02           hc5e2d97_0    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
referencing               0.30.0             pyhd8ed1ab_0    conda-forge
reportlab                 4.0.4           py311heffc1b2_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rlpycairo                 0.2.0              pyhd8ed1ab_0    conda-forge
rpds-py                   0.9.2           py311h0563b04_0    conda-forge
sander                    22.0                     pypi_0    pypi
scipy                     1.11.1          py311h93d07a4_0    conda-forge
send2trash                1.8.2              pyhd1c38e8_0    conda-forge
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smirnoff99frosst          1.1.0              pyh44b312d_0    conda-forge
snappy                    1.1.10               h17c5cce_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlalchemy                2.0.19          py311heffc1b2_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
terminado                 0.17.1             pyhd1c38e8_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tinydb                    4.8.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.3.2           py311heffc1b2_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   2.0.4              pyhd8ed1ab_0    conda-forge
validators                0.20.0             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.6.1              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_1    conda-forge
widgetsnbextension        4.0.8              pyhd8ed1ab_0    conda-forge
xmltodict                 0.13.0             pyhd8ed1ab_0    conda-forge
org-kbproto              1.0.7             h27ca646_1002    conda-forge
xorg-libice               1.0.10               h27ca646_0    conda-forge
xorg-libsm                1.2.3             h27ca646_1000    conda-forge
xorg-libx11               1.8.6                hfd9643e_0    conda-forge
xorg-libxau               1.0.11               hb547adb_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xorg-libxext              1.3.4                h1a8c8d9_2    conda-forge
xorg-libxt                1.3.0                hb547adb_0    conda-forge
xorg-xextproto            7.3.0             h1a8c8d9_1003    conda-forge
xorg-xproto               7.0.31            h27ca646_1007    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
zeromq                    4.3.4                hbdafb3b_1    conda-forge
zipp                      3.16.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h53f4e23_5    conda-forge
zlib-ng                   2.0.7                h1a8c8d9_0    conda-forge
zstd                      1.5.2                h4f39d0f_7    conda-forge
```

</details>

**Comment by mikemhenry** [comment]
So:
`CONDA_SUBDIR=osx-64 micromamba --dry-run create -n foo openfe=0.11.1 python=3.10` works just fine but if we do it with python 3.11:
`CONDA_SUBDIR=osx-64 micromamba --dry-run create -n foo openfe=0.11.1 python=3.11` I get this error:

```
    The following packages are incompatible
    ├─ openfe 0.11.1**  is installable and it requires
    │  └─ lomap2 >=2.1.0 , which requires
    │     └─ matplotlib-base   with the potential options
    │        ├─ matplotlib-base [2.1.2|2.2.3|2.2.4] would require
    │        │  └─ python >=2.7,<2.8.0a0 , which can be installed;
    │        ├─ matplotlib-base [2.1.2|2.2.3|...|3.2.0] would require
    │        │  └─ python >=3.6,<3.7.0a0 , which can be installed;
    │        ├─ matplotlib-base [2.1.2|2.2.3|...|3.2.0] would require
    │        │  └─ python >=3.7,<3.8.0a0 , which can be installed;
    │        ├─ matplotlib-base [2.2.4|3.1.1|3.1.2|3.1.3|3.2.0] would require
    │        │  └─ python >=3.8,<3.9.0a0 , which can be installed;
    │        ├─ matplotlib-base 2.2.5 would require
    │        │  └─ python_abi 2.7.* *_cp27m, which can be installed;
    │        ├─ matplotlib-base [2.2.5|3.2.1|...|3.3.4] would require
    │        │  └─ python_abi 3.6.* *_cp36m, which can be installed;
    │        ├─ matplotlib-base [2.2.5|3.2.1|...|3.5.3] would require
    │        │  └─ python_abi 3.7.* *_cp37m, which can be installed;
    │        ├─ matplotlib-base [2.2.5|3.2.1|...|3.5.3] would require
    │        │  └─ python_abi 3.8.* *_cp38, which can be installed;
    │        ├─ matplotlib-base [2.2.5|3.3.2|...|3.5.3] would require
    │        │  └─ python_abi 3.9.* *_cp39, which can be installed;
    │        ├─ matplotlib-base [3.2.2|3.3.0|...|3.3.4] would require
    │        │  └─ python_abi 3.6 *_pypy36_pp73, which can be installed;
    │        ├─ matplotlib-base [3.3.3|3.3.4|...|3.5.2] would require
    │        │  └─ python_abi 3.7 *_pypy37_pp73, which can be installed;
    │        ├─ matplotlib-base [3.4.3|3.5.0|3.5.1|3.5.2|3.5.3] would require
    │        │  └─ python_abi 3.10.* *_cp310, which can be installed;
    │        ├─ matplotlib-base [3.5.2|3.5.3] would require
    │        │  └─ python_abi 3.8 *_pypy38_pp73, which can be installed;
    │        ├─ matplotlib-base [3.5.2|3.5.3] would require
    │        │  └─ python_abi 3.9 *_pypy39_pp73, which can be installed;
    │        └─ matplotlib-base [3.6.0|3.6.1|...|3.7.2] would require
    │           └─ __osx >=10.12 , which is missing on the system;
    └─ python 3.11**  is uninstallable because it conflicts with any installable versions previously reported.
critical libmamba Could not solve for environment specs
```

Which looks like a virtual package, so it is probably a false positive on why it fails to resolve.

**Comment by mikemhenry** [comment]
We should probably open an issue on the conda-forge package about python 3.11 giving us issues, but I think this PR is good to go now

**Review by dwhswenson — APPROVED** [review]
LGTM. I'm hoping we'll be able to get the osx-arm64 special instructions removed soon, but this is a nice improvement

**Pull request merged**
