### PR TITLE
Optional codecov failures

### LINKED ISSUE #195: make codecov optional?
codecov fails sometimes and counts as a build fail.  Can we alter the CI to consider uploading to codecov as optional?

### PR DESCRIPTION
**Pull request by IAlibay**
Fixes #195 

I generally don't mind having fail CI but codecov has been quite flaky lately.

### CODE REVIEW

**Comment by richardjgowers** [comment]
ah, that was easier than I thought

**Comment by IAlibay** [comment]
#scienceteam

**Comment by dwhswenson** [comment]
Can we instead see about adding the codecov token? The error claims that should fix it.

**Comment by IAlibay** [comment]
> Can we instead see about adding the codecov token? The error claims that should fix it.

Which particular action was failing? We've been having a lot of flaky connection errors (that usually manifest as something else), in the MDA repos. If there's a different error we should definitely address it.

**Comment by IAlibay** [comment]
Found it, seems to be this issue: https://github.com/codecov/codecov-action/issues/598 seems to be quite a widespread problem.

**Comment by dwhswenson** [comment]
e.g. https://github.com/OpenFreeEnergy/gufe/actions/runs/3316057928/jobs/5477405231#step:10:68

[2022-10-24T20:48:33.760Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}

This sounds to me like it is problem with CodeCov contacting GitHub Actions, and if we give explicit information we can fix it.

**Comment by IAlibay** [comment]
> e.g. https://github.com/OpenFreeEnergy/gufe/actions/runs/3316057928/jobs/5477405231#step:10:68
> 
> [2022-10-24T20:48:33.760Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
> 
> This sounds to me like it is problem with CodeCov contacting GitHub Actions, and if we give explicit information we can fix it.

We can do, although I will point out that codecov specifically outlines that tokens are not necessary for github actions.

**Comment by dwhswenson** [comment]
> We can do, although I will point out that codecov specifically outlines that tokens are not necessary for github actions on public repos

I think that's a matter of "we have a method to get that info without the token if it is public." I think the method that they have is flaky, and that's our problem.

**Review by dwhswenson — APPROVED** [review]

**Pull request merged**
