### PR TITLE
Log system probe info

### PR DESCRIPTION
**Pull request by dwhswenson**
This is a follow-up to #505. Here we add a convenience for more user-friendly logging of the most important information for particular hardware. This also makes logging this the first step in our `_execute` for our protocol units (idea being that we'd like to see things like memory leaks when we run these in series.)

I'm not sure whether we want this on or off by default. Usually I push for less output, but I think we'll want this as a first check on failures (especially the segfaults that we've had reported).

Current output from quickrun on my machine:

```
Loading file...
Planning simulations for this edge...
Starting the simulations for this edge...
SYSTEM CONFIG DETAILS:
hostname: 'Yvette.local'
CUDA-based GPU not found
Memory used: 1.8G (95.7%)
/dev/disk3s1s1: 5%% full (276Gi free)
devfs: 100%% full (0Bi free)
/dev/disk3s6: 3%% full (276Gi free)
/dev/disk3s2: 1%% full (276Gi free)
/dev/disk3s4: 1%% full (276Gi free)
/dev/disk1s2: 2%% full (481Mi free)
/dev/disk1s1: 2%% full (481Mi free)
/dev/disk1s3: 1%% full (481Mi free)
/dev/disk3s5: 70%% full (276Gi free)
map: 0Bi% full (0Bi free)
Preparing the hybrid topology simulation
Parameterizing molecules
```

I'm a little confused on some of the numbers (as I mentioned in https://github.com/OpenFreeEnergy/openfe/pull/505#issuecomment-1659271197, the `df` output is essentially nonsense except `/dev/disk3s5`; also, I'm not sure how 1.8G is 95.7% of my 24GB machine, but to be fair, Apple does a lot of magic with memory compression behind the scenes, plus this is running under x86-64 emulation.)

TODO
- [x] Implement logging wrapper for `_probe_system`
- [x] Test that system probe isn't called if loggers aren't enabled
- [x] Unit test for `log_system_probe`

## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT License [here](https://github.com/OpenFreeEnergy/openfe/blob/main/LICENSE) and the **Developer Certificate of Origin** at <https://developercertificate.org/>.

### CODE REVIEW

**Comment by dwhswenson** [comment]
This should be ready for review. We can easily add/change what gets included here; but this is a start.

**Comment by mikemhenry** [comment]
Yah `df` isn't perfect and the output can be crazy depending on how the system is setup:
```
(openfe-0.11) [henrym3@lilac-ln02 ~]$ df -h
Filesystem                              Size  Used Avail Use% Mounted on
/dev/vda2                                90G   30G   60G  34% /
devtmpfs                                 63G     0   63G   0% /dev
tmpfs                                    63G  644K   63G   1% /dev/shm
tmpfs                                    63G   14M   63G   1% /run
tmpfs                                    63G     0   63G   0% /sys/fs/cgroup
/dev/vdb1                               200G   10G  190G   5% /scratch
/dev/vda5                               4.9G  3.5G  1.5G  71% /var
/dev/vda1                               997M  147M  851M  15% /boot
/dev/vda3                               4.9G  2.8G  2.1G  58% /tmp
admin                                    56T   48T  8.4T  86% /admin
lilac                                   4.1P  3.4P  695T  84% /lila
tmpfs                                    13G     0   13G   0% /run/user/20139
tmpfs                                    13G     0   13G   0% /run/user/20095
tmpfs                                    13G     0   13G   0% /run/user/164091798
tmpfs                                    13G     0   13G   0% /run/user/164016211
tmpfs                                    13G     0   13G   0% /run/user/20128
tmpfs                                    13G     0   13G   0% /run/user/1794
tmpfs                                    13G     0   13G   0% /run/user/164040457
tmpfs                                    13G     0   13G   0% /run/user/164091920
tmpfs                                    13G     0   13G   0% /run/user/164048130
tmpfs                                    13G     0   13G   0% /run/user/1770
tmpfs                                    13G     0   13G   0% /run/user/1706
tmpfs                                    13G     0   13G   0% /run/user/1454
tmpfs                                    13G     0   13G   0% /run/user/1566
oscar                                   4.0P  3.6P  380T  91% /oscar
tmpfs                                    13G     0   13G   0% /run/user/164090198
10.230.1.196:/admin/home/vallerul        56T   48T  8.4T  86% /sysadmin/home/vallerul
10.230.1.197:/admin/home/tartaglf        56T   48T  8.4T  86% /sysadmin/home/tartaglf
rtsia01-private:/ifs/prod/warm          6.8P  2.4P  4.4P  35% /ifs/rtsia01
rtsia01-private:/ifs/prod/warm/chodera   60T   47T   14T  78% /ifs/rtsia01/chodera
tmpfs                                    13G     0   13G   0% /run/user/1757
tmpfs                                    13G     0   13G   0% /run/user/1951
tmpfs                                    13G     0   13G   0% /run/user/163728041
tmpfs                                    13G     0   13G   0% /run/user/20137
tmpfs                                    13G     0   13G   0% /run/user/164013714
tmpfs                                    13G     0   13G   0% /run/user/164057129
tmpfs                                    13G     0   13G   0% /run/user/164077771
tmpfs                                    13G     0   13G   0% /run/user/1958
tmpfs                                    13G     0   13G   0% /run/user/1564
tmpfs                                    13G     0   13G   0% /run/user/1417
tmpfs                                    13G     0   13G   0% /run/user/0
tmpfs                                    13G     0   13G   0% /run/user/1142
tmpfs                                    13G     0   13G   0% /run/user/1662
tmpfs                                    13G     0   13G   0% /run/user/164055460
tmpfs                                    13G     0   13G   0% /run/user/20124
tmpfs                                    13G     0   13G   0% /run/user/163969241
tmpfs                                    13G     0   13G   0% /run/user/164091909
tmpfs                                    13G     0   13G   0% /run/user/164088136
tmpfs                                    13G     0   13G   0% /run/user/164091781
tmpfs                                    13G     0   13G   0% /run/user/1329
tmpfs                                    13G     0   13G   0% /run/user/164049964
tmpfs                                    13G     0   13G   0% /run/user/164094453
10.2.0.34:/igo/delivery                 3.0P  2.6P  401T  87% /igo/delivery
tmpfs                                    13G     0   13G   0% /run/user/1917
tmpfs                                    13G     0   13G   0% /run/user/164063509
tmpfs                                    13G     0   13G   0% /run/user/1630
tmpfs                                    13G     0   13G   0% /run/user/1749
tmpfs                                    13G     0   13G   0% /run/user/164093076
tmpfs                                    13G     0   13G   0% /run/user/6040
tmpfs                                    13G     0   13G   0% /run/user/164064257
tmpfs                                    13G     0   13G   0% /run/user/164091938
tmpfs                                    13G     0   13G   0% /run/user/1452
tmpfs                                    13G     0   13G   0% /run/user/1585
tmpfs                                    13G     0   13G   0% /run/user/1272
tmpfs                                    13G     0   13G   0% /run/user/1987
tmpfs                                    13G     0   13G   0% /run/user/1382
tmpfs                                    13G     0   13G   0% /run/user/164072191
tmpfs                                    13G     0   13G   0% /run/user/20069
tmpfs                                    13G     0   13G   0% /run/user/164048113
tmpfs                                    13G     0   13G   0% /run/user/1775
tmpfs                                    13G     0   13G   0% /run/user/1544
tmpfs                                    13G     0   13G   0% /run/user/164091649
tmpfs                                    13G     0   13G   0% /run/user/1653
rtsia01-private:/ifs/prod/warm/fwlab     40T   11T   30T  27% /ifs/rtsia01/fwlab
tmpfs                                    13G     0   13G   0% /run/user/7009
tmpfs                                    13G     0   13G   0% /run/user/1944
tmpfs                                    13G     0   13G   0% /run/user/1447
tmpfs                                    13G     0   13G   0% /run/user/164088122
tmpfs                                    13G     0   13G   0% /run/user/1474
tmpfs                                    13G     0   13G   0% /run/user/164060749
tmpfs                                    13G     0   13G   0% /run/user/1143
tmpfs                                    13G     0   13G   0% /run/user/1439
tmpfs                                    13G     0   13G   0% /run/user/6080
tmpfs                                    13G     0   13G   0% /run/user/1801
tmpfs                                    13G     0   13G   0% /run/user/164094524
tmpfs                                    13G     0   13G   0% /run/user/1984
tmpfs                                    13G     0   13G   0% /run/user/164085132
tmpfs                                    13G     0   13G   0% /run/user/1465
tmpfs                                    13G     0   13G   0% /run/user/1886
tmpfs                                    13G     0   13G   0% /run/user/164074907
tmpfs                                    13G     0   13G   0% /run/user/7027
tmpfs                                    13G     0   13G   0% /run/user/164060514
tmpfs                                    13G     0   13G   0% /run/user/164030255
tmpfs                                    13G     0   13G   0% /run/user/7020
tmpfs                                    13G     0   13G   0% /run/user/1613
tmpfs                                    13G     0   13G   0% /run/user/164088823
tmpfs                                    13G     0   13G   0% /run/user/164091585
tmpfs                                    13G     0   13G   0% /run/user/1631
tmpfs                                    13G     0   13G   0% /run/user/164084959
tmpfs                                    13G     0   13G   0% /run/user/164091824
tmpfs                                    13G     0   13G   0% /run/user/164080515
tmpfs                                    13G     0   13G   0% /run/user/164093380
tmpfs                                    13G     0   13G   0% /run/user/1948
tmpfs                                    13G     0   13G   0% /run/user/1866
tmpfs                                    13G     0   13G   0% /run/user/1957
tmpfs                                    13G     0   13G   0% /run/user/164091933
tmpfs                                    13G     0   13G   0% /run/user/164046762
tmpfs                                    13G     0   13G   0% /run/user/164059135
tmpfs                                    13G     0   13G   0% /run/user/164088754
tmpfs                                    13G     0   13G   0% /run/user/164088187
tmpfs                                    13G     0   13G   0% /run/user/1705
tmpfs                                    13G     0   13G   0% /run/user/1227
tmpfs                                    13G     0   13G   0% /run/user/1942
tmpfs                                    13G     0   13G   0% /run/user/1968
```

If there was a clean way to know where a user is going to be putting files, we could only check those mount points, maybe for this first pass we don't include `df` output since it might be worse than having it. At least with running out of diskspace, if we get a user saying "weird I am getting what looks like a permissions issue" we can say "check how much diskspace you have"

**Comment by dwhswenson** [comment]
> If there was a clean way to know where a user is going to be putting files

We know the directory. You should be able to get the appropriate mount point from that, right? Can you update this to take `Optional[Iterable[pathlib.Path]]` which restricts to the relevant mount points, and gives current behavior if not specified?

**Comment by mikemhenry** [comment]
> > If there was a clean way to know where a user is going to be putting files
> 
> We know the directory. You should be able to get the appropriate mount point from that, right? Can you update this to take `Optional[Iterable[pathlib.Path]]` which restricts to the relevant mount points, and gives current behavior if not specified?

Do you want that in a seperate PR? I can do that. When I was writing the system probe, I didn't think about making things optional, I was thinking that we needed to be able to call it at any point. Should have thought about if we know more, then we should use it!

**Comment by dwhswenson** [comment]
> Do you want that in a separate PR?

Either way. I'm on mobile now and won't be dealing with anything for the next week.

**Comment by mikemhenry** [comment]
PR here https://github.com/OpenFreeEnergy/openfe/pull/519

**Review by richardjgowers — APPROVED** [review]

**Comment by dwhswenson** [comment]
I think that CodeCov has lost its mind. It's claiming missing coverage on a bunch of stuff that isn't in this PR.

Anyway, this should be ready for review/merge.

**Comment by mikemhenry** [comment]
> I think that CodeCov has lost its mind. It's claiming missing coverage on a bunch of stuff that isn't in this PR.

It is having a winge because the long tests are not running on this PR since we only run those nightly, but it is trying to tell us "hey this PR makes tests that normally run not run" but it is just confused about that. I think we talked about adding some flags to change that behavior but we haven't gotten around to it yet

**Review by richardjgowers — APPROVED** [review]

**Pull request merged**
