### PR TITLE
fix issue with new notebook version

### PR DESCRIPTION
**Pull request by mikemhenry**
## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT License [here](https://github.com/OpenFreeEnergy/openfe/blob/main/LICENSE) and the **Developer Certificate of Origin** at <https://developercertificate.org/>.

### CODE REVIEW

**Comment by mikemhenry** [comment]
Got this error in CI:
`/home/runner/openfeforge/bin/.widgetsnbextension-post-link.sh: line 1: /home/runner/openfeforge/bin/jupyter-nbextension: No such file or directory` 

It was working last week, looks like there was a bump in the major version of `notebook` so that may be the cause, still investigating

**Comment by mikemhenry** [comment]
https://github.com/OpenFreeEnergy/openfe/actions/runs/5532705672

Looks like it worked!

**Comment by mikemhenry** [comment]
This one is ready for review!

**Review by dwhswenson — APPROVED** [review]
Looks good as a band-aid, but:

1. Is this something that is going to bite us elsewhere? (Thinking ExampleNotebooks in particular).
2. From pinning, I assume this means something in our stack needs to update to meet to new major version changes. Do we know who we're waiting on?

**Comment by mikemhenry** [comment]
The error I got was:
`/home/runner/openfeforge/bin/.widgetsnbextension-post-link.sh: line 1: /home/runner/openfeforge/bin/jupyter-nbextension: No such file or directory` 

But the actual `jupyter-nbextension` package was the same in the CI that passed last week and the one the failed today. So I agree it is a band-aid and I really don't have a good answer to your questions. The good news :tm: is that with the way the installer works, since it gets tested, we know that it will work if someone uses it.

**Pull request merged**
