### PR TITLE
Get ExampleNotebooks into docs

### PR DESCRIPTION
**Pull request by Yoshanuikabundi**
This PR is all about getting notebooks from https://github.com/OpenFreeEnergy/ExampleNotebooks/ into the docs.

## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT License [here](https://github.com/OpenFreeEnergy/openfe/blob/main/LICENSE) and the **Developer Certificate of Origin** at <https://developercertificate.org/>.

### CODE REVIEW

**Comment by Yoshanuikabundi** [comment]
This one depends on https://github.com/OpenFreeEnergy/ExampleNotebooks/pull/81

**Comment by Yoshanuikabundi** [comment]
This is ready for review once https://github.com/OpenFreeEnergy/ExampleNotebooks/pull/84 is merged!

**Comment by dwhswenson** [comment]
Close/reopen to trigger CI build, now that https://github.com/OpenFreeEnergy/ExampleNotebooks/pull/84 is merged.

**Review by dwhswenson — APPROVED** [review]
Looks good! (to within that 1 Safari CSS issue) Builds fine now that the ExampleNotebooks PR is in.

**Pull request merged**
