### PR TITLE
Remove top level settings class entry

### LINKED ISSUE #413: Remove openfe.protocols.openmm_rfe.equil_rfe_settings.RelativeHybridTopologyProtocolSettings from settings docs
It's not giving a correct overview of the settings (missing thermo and force field settings).

### PR DESCRIPTION
**Pull request by IAlibay**
Fixes #413

### CODE REVIEW

**Review by richardjgowers — CHANGES_REQUESTED** [review]
not sure I agree with this one.  I would rather we include the inherited settings members?

**Comment by IAlibay** [comment]
> not sure I agree with this one. I would rather we include the inherited settings members?

how

**Comment by IAlibay** [comment]
@richardjgowers - now you have BaseSettings (points to nothing) and a ThermoSettings entry that has a broken link.

**Comment by IAlibay** [comment]
Fixed by much bettter people.

**Pull request closed without merging**
