### PR TITLE
Set up basic mypy CI

### PR DESCRIPTION
**Pull request by IAlibay**
There's some failing mypy tests revolving around rdkit and networkx.

### CODE REVIEW

**Comment by richardjgowers** [comment]
@IAlibay what does the `Generic[]` thing do?

**Comment by IAlibay** [comment]
> @IAlibay what does the `Generic[]` thing do?

Hold for a sec this is a test to see if CI stops being red. I've not had time to fully read into this:
https://docs.python.org/3/library/typing.html#user-defined-generic-types

**Comment by IAlibay** [comment]
> @IAlibay what does the `Generic[]` thing do?

Didn't see #48 come in - removed.

There is an issue with concurrency though, I need to work out what's going on with the workflow names.

**Comment by IAlibay** [comment]
> There is an issue with concurrency though, I need to work out what's going on with the workflow names.

There we go - problem fixed.

**Review by richardjgowers — APPROVED** [review]

**Pull request merged**
