### PR TITLE
network_from_indices raises warning on disconnected network

### PR DESCRIPTION
**Pull request by richardjgowers**
fixes issue #510

removes LigandNetwork in favour of implementation in gufe

## Developers certificate of origin
- [ ] I certify that this contribution is covered by the MIT License [here](https://github.com/OpenFreeEnergy/openfe/blob/main/LICENSE) and the **Developer Certificate of Origin** at <https://developercertificate.org/>.

### CODE REVIEW

**Comment by IAlibay** [comment]
Did we not fully switch to using `gufe`'s LigandNetwork? https://github.com/OpenFreeEnergy/openfe/blob/main/openfe/setup/ligand_network.py

**Comment by richardjgowers** [comment]
looks like we forgot to remove it from here when we migrated it

**Comment by IAlibay** [comment]
Huh, did graphml update and now things are zero indexed?

**Comment by IAlibay** [comment]
pinging @dwhswenson on graphml failures here

**Comment by dwhswenson** [comment]
It looks to me like changes to the `LigandNetwork` in https://github.com/OpenFreeEnergy/gufe/pull/195 affected order of resulting sets in serialization. The template files in this repository are no longer accurate. Note: Among those changes, we no longer include version of the software that generated it in the GraphML, which would also cause a problem here if the order had not.

You can fix this by either:

1. Updating the template files by running the `tests/dev/serialization_test_templates.py` script and moving the output `network_template.graphml` to the `tests/data/serialization` directory; or
2. Removing the entirety of the `tests/setup/test_network.py` file -- it should have already been transferred over to gufe, right? There's no need to keep 2 copies of the tests. While you're at it, remove the template GraphML file, and the parts of the code for the `serialization_test_templates`dealing with that.

IMO, reducing duplication (choice 2) is probably the better path.

**Pull request merged**
